cmake_minimum_required(VERSION 3.27)
project(House_Simulator)

set(CMAKE_CXX_STANDARD 20)

add_executable(House_Simulator main.cpp
        app/house/house.cpp
        app/house/house.h
        app/house/room.cpp
        app/house/room.h
        app/exceptions/positionOcuppied.h
        app/house/houseElements.cpp
        app/house/houseElements.h
        app/exceptions/roomNotFound.h
        app/house/room/sensors/sensor.cpp
        app/house/room/sensors/sensor.h
        app/house/room/devices/devices.cpp
        app/house/room/devices/devices.h
        app/house/room/processor.cpp
        app/house/room/processor.h
        app/house/room/processor/rules/rule.cpp
        app/house/room/processor/rules/rule.h
        app/house/room/processor/rules/equalTo.cpp
        app/house/room/processor/rules/equalTo.h
        app/house/room/processor/rules/lessThan.cpp
        app/house/room/processor/rules/lessThan.h
        app/house/room/processor/rules/greaterThan.cpp
        app/house/room/processor/rules/greaterThan.h
        app/house/room/processor/rules/within.cpp
        app/house/room/processor/rules/within.h
        app/house/room/processor/rules/outsideOf.cpp
        app/house/room/processor/rules/outsideOf.h
        app/house/room/devices/cooler.cpp
        app/house/room/devices/cooler.h
        app/house/room/devices/heater.cpp
        app/house/room/devices/heater.h
        app/house/room/devices/sprinkler.cpp
        app/house/room/devices/sprinkler.h
        app/house/room/devices/lamp.cpp
        app/house/room/devices/lamp.h
        app/house/room/sensors/smokeSensor.cpp
        app/house/room/sensors/smokeSensor.h
        app/house/room/sensors/humiditySensor.cpp
        app/house/room/sensors/humiditySensor.h
        app/house/room/sensors/luminositySensor.cpp
        app/house/room/sensors/luminositySensor.h
        app/house/room/sensors/movementSensor.cpp
        app/house/room/sensors/movementSensor.h
        app/house/room/sensors/radiationSensor.cpp
        app/house/room/sensors/radiationSensor.h
        app/house/room/sensors/soundSensor.cpp
        app/house/room/sensors/soundSensor.h
        app/house/room/sensors/temperatureSensor.cpp
        app/house/room/sensors/temperatureSensor.h
        app/exceptions/invalidPosition.h
        app/house/room/propertys/property.cpp
        app/house/room/propertys/property.h
        app/house/room/propertys/temperature.cpp
        app/house/room/propertys/temperature.h
        app/house/room/propertys/vibration.cpp
        app/house/room/propertys/vibration.h
        app/house/room/propertys/luminosity.cpp
        app/house/room/propertys/luminosity.h
        app/house/room/propertys/radiation.cpp
        app/house/room/propertys/radiation.h
        app/house/room/propertys/humidity.cpp
        app/house/room/propertys/humidity.h
        app/house/room/propertys/sound.cpp
        app/house/room/propertys/sound.h
        app/house/room/propertys/smoke.cpp
        app/house/room/propertys/smoke.h
        app/exceptions/invalidDeviceType.h
        app/exceptions/invalidSensorType.h
        app/exceptions/outOfRangeProperty.h
        app/exceptions/processorNotFound.h
        app/exceptions/unknowRule.h
        app/exceptions/sensorNotFound.h
        app/exceptions/ruleNotFound.h
        app/exceptions/deviceNotFound.h
        app/exceptions/acessError.h
        app/exceptions/nameAlreadyExists.h
        app/exceptions/nameNotFound.h
        app/app.cpp
        app/app.h
        app/terminal/Terminal.cpp
        app/exceptions/commandNotFound.h
        app/exceptions/fileNotOpened.h
        app/exceptions/houseNotCreated.h
)
target_link_libraries(${PROJECT_NAME} C:/Users/guilh/Documents/GitHub/House-Simulator/pdcurses.a)